version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: hipposearch
    ports:
        - "127.0.0.1:9200:9200"
    environment:
      http.host: "0.0.0.0"
      transport.host: "127.0.0.1"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
      bootstrap.memory_lock: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - hipponet

  hippocampe:
    build: .
    container_name: hippocampe
    ports:
      - "5000:5000"
    networks:
      - hipponet
    depends_on:
      - elasticsearch

networks:
  hipponet:
    driver: bridge
